WebsiteMVC/WebsiteMVC/Models/TaiKhoan.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.DuAns = new HashSet<DuAn>();
            this.Houses = new HashSet<House>();
            this.TinTucs = new HashSet<TinTuc>();
        }
    
        public int IDTaiKhoan { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Avatar { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Adress { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string POSITION { get; set; }
        public Nullable<byte> State { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuAn> DuAns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<House> Houses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinTuc> TinTucs { get; set; }
    }
}

WebsiteMVC/WebsiteMVC/Areas/AdminCP/Controllers/TaiKhoanController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteMVC.Models;

namespace WebsiteMVC.Areas.AdminCP.Controllers
{
    [RoleAccept(eRole.ADMIN)]
    public class TaiKhoanController : AdminController
    {
        // GET: TaiKhoan
        public ActionResult Index()
        {
            return View(db.TaiKhoans.ToList().Where(q => q.State != MState.DELETE).ToList());
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(string oldpass, string newpass, string repass)
        {
            if (newpass != repass)
            {
                ModelState.AddModelError("", "Xác nhận mật khẩu không chính xác.");
            }
            if (newpass.Length < 8)
            {
                ModelState.AddModelError("", "Nhập mật khẩu có ít nhất 08 tí tự.");
            }
            if (oldpass.Length < 0)
            {
                ModelState.AddModelError("", "Vui lòng nhập mật khẩu cũ.");
            }
            if (ModelState.ContainsKey("") == false)
            {
                var db = new Models.HOUSEEntities();
                var acc = db.TaiKhoans.FirstOrDefault(q => q.IDTaiKhoan == Account.IDTaiKhoan);
                if (acc.Password == oldpass)
                {
                    acc.Password = repass;
                    db.SaveChanges();
                    return RedirectToAction("Logout", "Login", new { area = "" });
                }
                ModelState.AddModelError("", "Mật khẩu cũ không chính xác");
            }
            return View();
        }

        // GET: TaiKhoan/Edit/5
        public ActionResult Edit(int? id)
        {
            TaiKhoan obj = new TaiKhoan();
            if (id > 0)
            {
                obj = db.TaiKhoans.Find(id);
                if (obj == null)
                {
                    return HttpNotFound();
                }
            }
            return View(obj);
        }

        // POST: TaiKhoan/Edit/5
        [HttpPost]
        public ActionResult Edit(TaiKhoan obj)
        {
            if (ModelState.IsValid)
            {
                obj.SaveFor(q => q.Avatar);

                if (obj.IDTaiKhoan > 0)
                {
                    db.Entry(obj).State = EntityState.Modified;
                }
                else
                {
                    db.TaiKhoans.Add(obj);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public JsonResult Delete(int? id)
        {
            TaiKhoan obj = db.TaiKhoans.Find(id);
            //db.TaiKhoans.Remove(obj);
            obj.State = MState.DELETE;
            return Json(db.SaveChanges());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebsiteMVC/WebsiteMVC/Areas/AdminCP/Views/TaiKhoan/ChangePassword.cshtml
@{
    ViewBag.Title = "ĐỔI MẬT KHẨU";
    Layout = "~/Areas/AdminCP/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading"><i class="fa fa-pencil"></i> @ViewBag.Title</div>
    <div class="panel-body">
        @using (Html.BeginForm())
        {
            <p class="text-danger">@Html.ValidationSummary()</p>
            <div class="form-group">
                <label class="control-label">Mật khẩu hiện tại</label>
                <input type="password" name="oldpass" class="form-control">
            </div>
            <div class="form-group">
                <label class="control-label">Mật khẩu mới</label>
                <input type="password" name="newpass" class="form-control">
            </div>
            <div class="form-group">
                <label class="control-label">Xác nhận lại mật khẩu mới</label>
                <input type="password" name="repass" class="form-control">
            </div>
            <div class="margin-top-10">
                <input type="submit" name="name" class="btn green" value=" Thay đổi" />
                <a href="/" class="btn btn-primary">
                    Trang chủ
                </a>
            </div>
        }
    </div>
</div>

WebsiteMVC/WebsiteMVC/Areas/AdminCP/Views/TaiKhoan/Edit.cshtml
@model WebsiteMVC.Models.TaiKhoan

@{
    ViewBag.Title = "TÀI KHOẢN";
    Layout = "~/Areas/AdminCP/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading"><i class="fa fa-pencil"></i> @ViewBag.Title</div>
    <div class="panel-body">

        @using (Html.BeginForm("Edit", "TaiKhoan", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IDTaiKhoan)
                @Html.HiddenFor(model => model.State)
                @Html.HiddenFor(model => model.Avatar)

                <div class="form-group">
                    @Html.LabelFor(model => model.FullName, "Họ tên (*)", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.FullName, new { @class = "form-control", required = "true" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Username, "Tên đăng nhập (*)", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Username, new { @class = "form-control", required = "true" })
                    </div>
                </div>

                @if (Model.IDTaiKhoan == 0)
                {
                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, "Mật khẩu (*)", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Password, new { @class = "form-control", required = "true" })
                        </div>
                    </div>
                }
                else
                {
                    @Html.HiddenFor(q => q.Password);
                }

                <div class="form-group">
                    @Html.LabelFor(model => model.Avatar, "Ảnh đại diện", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <img src="@Model.Avatar" alt="<chưa có ảnh>" />
                        <br />
                        <input type="file" name="Avatar" value="" />
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Birthday, "Ngày sinh (*)", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Birthday, new { required = "true", type = "date", Value = Model.Birthday?.ToString("yyyy-MM-dd") })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Adress, "Địa chỉ (*)", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Adress, new { @class = "form-control", required = "true" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, "Điện thoại (*)", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", required = "true" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, "Email (*)", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Email, new { @class = "form-control", required = "true", type = "email" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.POSITION, "Chức vụ (*)", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <select required class="form-control" name="POSITION" id="POSITION">
                            <option value="">Vui lòng chọn</option>
                            <option value="ADMIN">Admin</option>
                            <option value="QUANLY">Quản lý</option>
                            <option value="CHUYENVIEN">Chuyên viên</option>
                            <option value="USER">User</option>
                        </select>

                        <script>
                            $("#POSITION").val('@Model.POSITION');
                        </script>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, "Thông tin thêm", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Description, new { @class = "form-control", Rows = "20" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Lưu" class="btn green" />
                        <a href="@Url.Action("Index")" class="btn btn-default"><i class="fa fa-arrow-circle-o-left"></i> QUAY LẠI DANH SÁCH</a>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

WebsiteMVC/WebsiteMVC/Areas/AdminCP/Views/TaiKhoan/Index.cshtml
@model IEnumerable<WebsiteMVC.Models.TaiKhoan>

@{
    ViewBag.Title = "DANH SÁCH TÀI KHOẢN";
    Layout = "~/Areas/AdminCP/Views/Shared/_LayoutAdmin.cshtml";
    var accept = WebsiteMVC.Models.LoginHelper.CheckRole(WebsiteMVC.Models.eRole.ADMIN);
}

<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-edit"></i>@ViewBag.Title
        </div>
    </div>
    <div class="portlet-body">
        @if (accept)
        {
            <div class="table-toolbar">
                <div class="row">
                    <div class="col-md-6">
                        <div class="btn-group">
                            <a href="@Url.Action("Edit")" id="sample_editable_1_new" class="btn green">
                                Thêm <i class="fa fa-plus"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }

        <table class="table table-bordered" id="table">
            <thead>
                <tr>
                    <th>
                        HỌ TÊN
                    </th>
                    <th>
                        ẢNH
                    </th>
                    <th>
                        TÊN ĐĂNG NHẬP
                    </th>
                    <th>
                        SDT
                    </th>
                    <th>
                        EMAIL
                    </th>
                    <th>
                        CHỨC VỤ
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td>
                            <img src="@item.Avatar" style="max-height: 30px" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Username)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Phone)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.POSITION)
                        </td>
                        <td>
                            @if (accept)
                            {
                                <a href="@Url.Action("Edit",new { id = item.IDTaiKhoan})" class="btn btn-primary" title="Sửa"><i class="fa fa-pencil"></i></a>
                                <span onclick="delete_object(this,'@item.IDTaiKhoan')" class="btn btn-warning" title="Xóa"><i class="fa fa-trash-o"></i></span>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>

@if (accept)
{

    @section css{
        <link href="/Content/theme/assets/global/plugins/datatables/media/css/jquery.dataTables.min.css" rel="stylesheet" />
    }

    @section js{
        <script type="text/javascript" src="/Content/theme/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="/Content/theme/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>

        <script>
        $("#table").DataTable();

        function delete_object(target, id) {
            if (confirm("Bạn có muốn xóa không?")) {
                $.ajax({
                    url: "@Url.Action("Delete")",
                    type: "POST",
                    data: { id: id },
                    success: function (d) {
                        if (d) {
                            $(target).closest("tr").remove();
                        } else {
                            alert("Xóa thất bại");
                        }
                    }
                })
            }
        }
        </script>
    }

}