WebsiteMVC/WebsiteMVC/Models/TinTuc.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int IDTinTuc { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public string Contents { get; set; }
        public string Avatar { get; set; }
        public Nullable<byte> State { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}

WebsiteMVC/WebsiteMVC/Areas/AdminCP/Controllers/TinTucController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteMVC.Models;

namespace WebsiteMVC.Areas.AdminCP.Controllers
{
    public class TinTucController : AdminController
    {
        // GET: AdminCP/TinTucs
        public ActionResult Index()
        {
            var tinTucs = db.TinTucs.Include(t => t.TaiKhoan);
            return View(tinTucs.ToList());
        }

        // GET: AdminCP/TinTucs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // GET: AdminCP/TinTucs/Create
        public ActionResult Create()
        {
            ViewBag.CreateBy = new SelectList(db.TaiKhoans, "IDTaiKhoan", "Username");
            return View();
        }

        // POST: AdminCP/TinTucs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDTinTuc,Title,CreateTime,CreateBy,Contents,Avatar")] TinTuc tinTuc)
        {
            if (ModelState.IsValid)
            {
                db.TinTucs.Add(tinTuc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CreateBy = new SelectList(db.TaiKhoans, "IDTaiKhoan", "Username", tinTuc.CreateBy);
            return View(tinTuc);
        }

        // GET: AdminCP/TinTucs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            ViewBag.CreateBy = new SelectList(db.TaiKhoans, "IDTaiKhoan", "Username", tinTuc.CreateBy);
            return View(tinTuc);
        }

        // POST: AdminCP/TinTucs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDTinTuc,Title,CreateTime,CreateBy,Contents,Avatar")] TinTuc tinTuc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tinTuc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CreateBy = new SelectList(db.TaiKhoans, "IDTaiKhoan", "Username", tinTuc.CreateBy);
            return View(tinTuc);
        }

        // GET: AdminCP/TinTucs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TinTuc tinTuc = db.TinTucs.Find(id);
            if (tinTuc == null)
            {
                return HttpNotFound();
            }
            return View(tinTuc);
        }

        // POST: AdminCP/TinTucs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TinTuc tinTuc = db.TinTucs.Find(id);
            db.TinTucs.Remove(tinTuc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

WebsiteMVC/WebsiteMVC/Controllers/TinTucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebsiteMVC.Controllers
{
    public class TinTucController : BaseController
    {
        // GET: TinTuc
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TopTinTuc()
        {
            var lst = db.TinTucs.OrderBy(q => q.CreateTime).Take(5).ToList();
            return View(lst);
        }

        public ActionResult Detail(int id)
        {
            return View(db.TinTucs.Find(id));
        }
    }
}

WebsiteMVC/WebsiteMVC/Views/TinTuc/TopTinTuc.cshtml
@model  IEnumerable<WebsiteMVC.Models.TinTuc>

<section class="bg-white">
    <div class="news-box">
        <div class="common-info">
            <h2>Thông tin thị trường</h2>
            <p>Góc nhìn thị trường, thông tin dự án và kiến thức giao dịch cần biết</p>
        </div>
        <section class="news-content main-content">
            <div class="bordertop-news01">
                <article class="featured">
                    @if (Model.Count() > 0)
                    {
                        <a href="@Url.Action("Index","TinTuc",new { id = Model.ElementAt(0).IDTinTuc })">
                            <div class="cover">
                                <img class="image-normalized" src="@(Model.ElementAt(0).Avatar)"
                                     alt="@(Model.ElementAt(0).Title)">
                            </div>
                        </a>
                        <header>
                            <div class="news">
                                <a href="@Url.Action("Detail","TinTuc",new { id = Model.ElementAt(0).IDTinTuc })">@(Model.ElementAt(0).Title)</a>
                            </div>
                            <p class="by">@(Model.ElementAt(0).CreateTime?.ToString("dd/MM/yyyy"))</p>
                            <p class="description"></p>
                        </header>
                    }
                </article>
            </div>
            <div class="bordertop-news02">
                @for (int i = 1; i < Model.Count(); i++)
                {
                    <article class="featured">
                        <a href="@Url.Action("Index","TinTuc",new { id = Model.ElementAt(i).IDTinTuc })">
                            <div class="cover">
                                <img class="image-normalized" src="@(Model.ElementAt(i).Avatar)"
                                     alt="@(Model.ElementAt(i).Title)">
                            </div>
                        </a>
                        <header>
                            <div class="news">
                                <a href="@Url.Action("Detail","TinTuc",new { id = Model.ElementAt(i).IDTinTuc })">@(Model.ElementAt(i).Title)</a>
                            </div>
                            <p class="by">@(Model.ElementAt(i).CreateTime?.ToString("dd/MM/yyyy"))</p>
                        </header>
                    </article>
                }

            </div>
            <div class="more-button-box mgt-0">
                <a class="black-button" href="#">Xem tất cả</a>
            </div>
        </section>
    </div>
</section>